data_dir: test_data/
test_dir: test_data/
inc_dir: incorrect_images/
media_dir: media/
model_dir: saved_models/
classes:
  - N/A
  - TOWAWAY
n_splits: 2
mobilenetv2:
  batch_size: 8
  eta: 0.0001
  patience: 1
  crop_size: 224
  degrees: 20
  hue: 0.3
  brightness: 0.2
  saturation: 0.2
  contrast: 0.2
  monitor: val_loss
  min_delta: 0
  lr_patience: 5
  factor: 0.5
  input_size:
    - 224
    - 224
  mean:
    - 0.485
    - 0.456
    - 0.406
  std:
    - 0.229
    - 0.224
    - 0.225
resnext101_32x4d:
  batch_size: 8
  eta: 0.0001
  patience: 1
  crop_size: 299
  degrees: 20
  hue: 0.3
  brightness: 0.2
  saturation: 0.2
  contrast: 0.2
  monitor: val_loss
  min_delta: 0
  lr_patience: 5
  factor: 0.5
  input_size:
    - 224
    - 224
  mean:
    - 0.485
    - 0.456
    - 0.406
  std:
    - 0.229
    - 0.224
    - 0.225
vggm:
  batch_size: 8
  eta: 0.0001
  patience: 1
  crop_size: 299
  degrees: 20
  hue: 0.3
  brightness: 0.2
  saturation: 0.2
  contrast: 0.2
  monitor: val_loss
  min_delta: 0
  lr_patience: 5
  factor: 0.5
  input_size:
    - 221
    - 221
  mean:
    - 123.68
    - 116.779
    - 103.939
  std:
    - 1
    - 1
    - 1
xception:
  batch_size: 8
  eta: 0.0001
  patience: 1
  crop_size: 299
  degrees: 20
  hue: 0.3
  brightness: 0.2
  saturation: 0.2
  contrast: 0.2
  monitor: val_loss
  min_delta: 0
  lr_patience: 5
  factor: 0.5
  input_size:
    - 299
    - 299
  mean:
    - 0.5
    - 0.5
    - 0.5
  std:
    - 0.5
    - 0.5
    - 0.5
inceptionv4:
  batch_size: 8
  eta: 0.0001
  patience: 1
  crop_size: 299
  degrees: 20
  hue: 0.3
  brightness: 0.2
  saturation: 0.2
  contrast: 0.2
  monitor: val_loss
  min_delta: 0
  lr_patience: 5
  factor: 0.5
  input_size:
    - 299
    - 299
  mean:
    - 0.5
    - 0.5
    - 0.5
  std:
    - 0.5
    - 0.5
    - 0.5
