# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Publish Package

on:
  release:
    types: [created]
    defaults:
      run:
        shell: bash -l {0}

jobs:
  deploy:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.6'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Conda environment creation and activation
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: pytorch_vision_dev
        python-version: 3.6
        environment-file: conda-envs/pytorch_vision_dev.yml    # Path to the build conda environment
        auto-update-conda: true
        auto-activate-base: false
        show-channel-urls: true
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERS }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        echo $CONDA/bin >> $GITHUB_PATH
        conda activate pytorch_vision_dev
        python setup.py sdist bdist_wheel
        twine upload dist/pytorch_vision_utils-0.3.6.tar.gz
