# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Publish Package

on:
  release:
    types: [created]

  jobs:
    deploy:
    build-and-test-env:
      runs-on: ubuntu-latest
      container: 
        image: ubuntu:latest
      steps:
      - uses: actions/checkout@v2
      - name: Build and publish
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERS }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: bash scripts/python-publish.sh
