# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Publish Package

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: 
      image: nclgbd/pytorchdev:0.3.11
      credentials:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}  
    steps:
    - uses: actions/checkout@v2
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERS }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      shell: bash -l {0}
      run: |
        ls -a
        conda activate pytorch_vision_dev
        bash scripts/python-publish.sh
