# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test Build Methods

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build-and-test-env:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v2
    - uses: iterative/setup-dvc@v1

    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6

    - name: Conda environment creation and activation
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: torch_base
        python-version: 3.6
        environment-file: conda-envs/torch_base.yml    # Path to the build conda environment
        auto-update-conda: true
        auto-activate-base: false
        show-channel-urls: true

    - name: Install dependencies
      run: |
        echo $CONDA/bin >> $GITHUB_PATH
        conda activate torch_base
        python -m pip install --upgrade pip
        
        git clone https://github.com/nclgbd/pretrained-models.pytorch.git
        cd pretrained-models.pytorch
        git pull origin master
        python setup.py install
        pip install -r requirements.txt
        cd ..

    - name: Run build and test scripts
      run: |
        echo $CONDA/bin >> $GITHUB_PATH
        conda activate torch_base
        ls -la
        python tests/run-tests.py

